### ISSUE TITLE
Fix string handling in aggregator "infrastructure" code.

### ISSUE THREAD

**Issue by kxyne** [cybergreen-net/cybergreen-etl2#21]
Haven't seen this before, I think the polling happened at the exact wrong moment, Regardless, fix the logging.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/logging/__init__.py", line 980, in emit
    msg = self.format(record)
  File "/usr/lib/python3.5/logging/__init__.py", line 830, in format
    return fmt.format(record)
  File "/usr/lib/python3.5/logging/__init__.py", line 567, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.5/logging/__init__.py", line 330, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "./cybergreen_tasks.py", line 10, in <module>
    luigi.run()
  File "/usr/local/lib/python3.5/dist-packages/luigi/interface.py", line 216, in run
    return _run(*args, **kwargs)['success']
  File "/usr/local/lib/python3.5/dist-packages/luigi/interface.py", line 244, in _run
    return _schedule_and_run([cp.get_task_obj()], worker_scheduler_factory)
  File "/usr/local/lib/python3.5/dist-packages/luigi/interface.py", line 203, in _schedule_and_run
    success &= worker.run()
  File "/usr/local/lib/python3.5/dist-packages/luigi/worker.py", line 1102, in run
    self._run_task(get_work_response.task_id)
  File "/usr/local/lib/python3.5/dist-packages/luigi/worker.py", line 920, in _run_task
    task_process.run()
  File "/usr/local/lib/python3.5/dist-packages/luigi/worker.py", line 194, in run
    new_deps = self._run_get_new_deps()
  File "/usr/local/lib/python3.5/dist-packages/luigi/worker.py", line 131, in _run_get_new_deps
    task_gen = self.task.run()
  File "/home/ubuntu/etl2/tasks/redshift_aggregation_pipeline.py", line 103, in run
    stop_redshift()
  File "/home/ubuntu/etl2/tasks/redshift_aggregation_pipeline.py", line 49, in stop_redshift
    rs.teardown()
  File "/home/ubuntu/etl2/infrastructure.py", line 154, in teardown
    logging.info('Redshift cluster is deleted', str(e))
Message: 'Redshift cluster is deleted'

**Comment by chorsley** [comment]
Updated formatting string in 8f12f6fbec.
